### ISSUE TITLE
Fix a few W3C HTML5 validation issues

### ISSUE THREAD

**Issue by gfairchild** [darshanbaral/aafu#1]
First off, I really love this theme. I'm working on migrating my site to it. However, I discovered a few simple HTML5 validation issues that should be fixed.

https://gfairchild.nfshost.com/ is the current temporary testing site for my new homepage. https://validator.w3.org/nu/?doc=https%3A%2F%2Fgfairchild.nfshost.com%2F shows the HTML5 validation results. There are a few things that stick out:

1. The Google font is incorrectly specified. This isn't your fault; this is Google's fault. As you can see [here](https://stackoverflow.com/a/22469221/1269634), all that you need to do is change `https://fonts.googleapis.com/css?family=Alegreya|Lato` to `https://fonts.googleapis.com/css?family=Alegreya%7CLato`.
1. The `<dl>` tag requires *both* at `<dt>` and `<dd>` tag to be valid. `layouts/partials/hobby.html` uses this tag incorrectly. There are a couple simple fixes you could do:
    1. You could replace the `<dl>` tag with a `<ul>` tag. You could use `style="list-style-type: none;"` to get rid of the bullet point and set the margin appropriately (e.g., [this](https://stackoverflow.com/a/19254469/1269634)) to create a visually similar look that adheres to the HTML5 spec.
    1. You could add a new optional `description` parameter to each hobby element to enable a user to optionally specify additional details about their hobby.
1. I haven't spent time to dig around, but it looks like `<h2>` and `<h3>` headings are used incorrectly in a few spots.

I love this theme, so keep up the good work!

**Comment by darshanbaral** [comment]
Thanks a lot @gfairchild. I have fixed the #1 and #2. The #3 is caused due to formatting issue so I may get to that later.

**Comment by gfairchild** [comment]
Great! Thank you, @darshanbaral. I can verify that the two errors were fixed.

**Comment by darshanbaral** [comment]
@gfairchild, now everything should be fine.

**Comment by gfairchild** [comment]
Everything looks good on my end! Thank you for fixing this so fast. I really like the theme.

**Comment by darshanbaral** [comment]
Thanks @gfairchild for the helpful comment.
