### ISSUE TITLE
Thanks for sharing this

### ISSUE THREAD

**Issue by eribertto** [darshanbaral/aafu#10]
Hello I hope this is not too much to ask but I like to know how to add links in the dot toml config file so they will appear when click in the one page portfolio. I'm trying to build mine for later hosting. I also cannot find how to remove the aafu instance beneath the profile pic circle.

I'm curious where to find the master control to tweak the variables in the dot toml file? Just a newbie here trying to learn web development and github. I'm learning Golang on the side if this can help me in the future. TIA.

**Comment by darshanbaral** [comment]
@eribertto, the newest update allows you to hide attribute if you want (I would request you to keep it if possible).

If you are referring to links for social icons or office or projects, you can just paste them under `url` or `thesis_link` or in the respective section (I will make sure to use only one term in the next update). If you want to add links in the markdown content (in about me text, for example),  you can add by typing `[emails](#)` where you need to replace `#` with your link. If I misunderstood your question, please let me know.
