### ISSUE TITLE
Localhost:1313 not work , i use ubuntu!

### ISSUE THREAD

**Issue by ahhhash** [darshanbaral/aafu#11]
UBUNTU:
i user your nice  Theme https://themes.gohugo.io/aafu/ .
i mak it like this :

    mkdir website
    hugo new site website
    i clone the the aafu theme on the themes
    cp -R themes/aafu/exampleSite/* .
    AND I START MY hugo server
    oh not work .

WHAT should I DO HERE TO SOLVE IT ?

INFO : i make the same on My mac .
is Work very good .

THANK YOU !

**Comment by ahhhash** [comment]
browsers can't load website. if run HUGO SERVER  on my ubuntu server, Firefox (itry also safari and google chrome) not reach the website (localhost:1313).
but if run HUGO SERVER on my Macbook, i can reach the website via Firefox

**Comment by ahhhash** [comment]
here is the issue i think , this block the webserver .

INFO 2020/02/26 08:00:07 No translation bundle found for default language "en"
INFO 2020/02/26 08:00:07 Translation func for language en not found, use default.
INFO 2020/02/26 08:00:07 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.

**Comment by darshanbaral** [comment]
@ahhhash, did you check here - https://discourse.gohugo.io/t/monolingual-site-getting-no-translation-bundle-warnings/6300

**Comment by ahhhash** [comment]
> @ahhhash, did you check here - https://discourse.gohugo.io/t/monolingual-site-getting-no-translation-bundle-warnings/6300

Hi ifix this issue. work fine .
