### ISSUE TITLE
Bug processing metas

### ISSUE THREAD

**Issue by gfairchild** [darshanbaral/aafu#12]
I'm using the latest Hugo (0.69.0) and latest version of this template (which I love!). You can see it [here](https://www.gfairchild.com/).

I just noticed that the `metas` block isn't being processed properly. Here's what I have in my `config.toml`:

```TOML
[params.favicons]
    use = true
    metas = '''
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">
    <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
    <link rel="shortcut icon" href="favicon.ico">
    '''
```

But when I look at the HTML, one line is botched pretty badly, and it's not longer compliant:

```html
<link rel="mask-icon" href="/safari-pinned-tab.svg color#252627">
```

As you can see, the `color` attribute isn't maintained, and it's combined into the `href`.

Looking at https://github.com/darshanbaral/aafu/blob/master/layouts/partials/meta.html#L11-L18, my guess is that the regex you've got going here just needs to be cleaned up a tad to make sure this doesn't happen.

**Comment by darshanbaral** [comment]
Can you check if the a4a626e0925311f65322c6162c8c176241fd3fb2 fixed it. Eventually, I'm hoping to move away from regex.

**Comment by gfairchild** [comment]
That fixed it! Thank you. :)
