### ISSUE TITLE
Blog pages not showing

### ISSUE THREAD

**Issue by thor314** [darshanbaral/aafu#16]
Following along with the Hugo [quickstart](https://gohugo.io/getting-started/quick-start/#readout). When I serve the site, and select the blog tab at the top, I'm getting 404 not found. Do you use some different file structure?
Update, I changed the name of the directory 'content/posts' to 'content/blog', and am now seeing my blog post, but when I click on the link, I'm getting a 404.
Last Update, I think I've solved my own issue. The default for Hugo is to keep posts in the `content/posts` directory. This theme is using the `content/blog` directory. Things seem to be working normally now; documentation for that would be helpful.

**Comment by RanitPradhan** [comment]
@thor314  I'm also having the same issue. Did you able to solve it ?

**Comment by thor314** [comment]
@RanitPradhan, the solution for my issue was that I wasn't cloning the submodule in which my theme lived. If you're cloning your repo, try `git clone --recurse-submodules`.

**Comment by RanitPradhan** [comment]
Okay.
