### ISSUE TITLE
Add enhanced favicon support

### ISSUE THREAD

**Issue by gfairchild** [darshanbaral/aafu#3]
A number of Hugo themes support some enhanced favicon support provided by a service like [RealFaviconGenerator](https://realfavicongenerator.net/) (e.g., [Hello Friend NG](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/README.md#favicon)). Would it be possible to include something like https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/layouts/partials/favicons.html in this theme?

**Comment by darshanbaral** [comment]
@gfairchild, I have implemented it in https://github.com/darshanbaral/aafu/commit/3d2728d2ce64daad54829c182f468ce646e96174. You can paste the links from the generator in `config.toml`. Please test and let me know if it works. I will then update the README.

**Comment by gfairchild** [comment]
This is great! Thank you very much. Everything appears to be working properly.
