### ISSUE TITLE
Request create sub heading on Publication and format journal following APA 6th

### ISSUE THREAD

**Issue by howieqq** [darshanbaral/aafu#5]
Dear Sir, 

Like the title, I would like to make a request to the author to create a sub-list on publication. 
For example: 
Publications
   Journal articles
   Proceeding

User click publications then will list journal articles and proceeding, if they click journal articles then see articles. In contrast, choose proceeding then just see only the list on this sub

Regards

**Comment by darshanbaral** [comment]
The publications section in the `config.toml`  of newest update provides a way to define the order of date, author, title, and journal name. You should be able to use that to define the `format` you want. You can also define `types` to group publications into different categories. I don't have plans to add animations or ways to show only one category at a time.

```
    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        format = ["date", "authors", "title", "journal"]
        types = ["Journal Articles", "Proceedings"]
```
