### ISSUE TITLE
theme is broken

### ISSUE THREAD

**Issue by rat-h** [darshanbaral/aafu#8]
I run `hugo` at pops linux (same as ubuntu 19)

```
hugo version
Hugo Static Site Generator v0.52/extended linux/amd64 BuildDate: 2018-12-21T15:59:29Z

```
here the problem. I installed aafu theme and ran just example
```
cd themes
git clone https://github.com/darshanbaral/aafu.git
Cloning into 'aafu'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (291/291), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 468 (delta 153), reused 209 (delta 86), pack-reused 177
Receiving objects: 100% (468/468), 1.37 MiB | 7.63 MiB/s, done.
Resolving deltas: 100% (244/244), done.
cd ../
cp themes/aafu/exampleSite/config.toml .
cp -a themes/aafu/static/images static/
```
but it returns an error
```
hugo server -D
Error: "... /themes/aafu/layouts/partials/meta.html:8:1": parse failed: template: partials/meta.html:8: function "hugo" not defined

```

**Comment by urjaacharya** [comment]
You might need to create a folder named `content` in the root of your site (parent directory of `themes`) and then run `hugo server`.

**Comment by rat-h** [comment]
I pretty sure, I have it. It is empty, but I had tried `hugo new content/_index.md` with no luck. It seems the problem in aafu

**Comment by darshanbaral** [comment]
@rat-h, what version of `hugo` are you using? It has been tested in `0.55.6` and may not work properly for older versions.

**Comment by rat-h** [comment]
@darshanbaral I had to build go and than hugo (both are quite old the standard repository, quite a shame). With version 0.57.0 aafu - works ok
